### Deployment ###
# It manages a set of identical pods, ensuring that the specified number of replicas are running at all times
kind: Deployment
apiVersion: apps/v1
metadata:
  name: housley-bouncer                           # The name of the Deployment
spec:
  replicas: 1                                     # The number of replicas to run
  selector:                                       # The selector for the pods that this Deployment manages
    matchLabels:
      app: housley-bouncer
  template:                                       # The template for the pods that this Deployment manages
    metadata:
      labels:                                     # The labels for the pods
        app: housley-bouncer
    spec:
      containers:
        - name: housley-bouncer-container         # The name of the container
          image: hlabs/housley_bouncer:latest     # The image to run in the container
          ports:
            - name: http                          # The port that the container is listening on
              containerPort: 8080
              protocol: TCP

